# Generated by Django 5.2.5 on 2025-08-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aula', models.CharField(max_length=10, unique=True, verbose_name='Número de Aula')),
                ('nombre_aula', models.CharField(max_length=100, verbose_name='Nombre del Aula')),
                ('tipo_aula', models.CharField(choices=[('Aula Teórica', 'Aula Teórica'), ('Laboratorio', 'Laboratorio'), ('Taller', 'Taller'), ('Auditorio', 'Auditorio'), ('Sala de computo', 'Sala de Cómputo'), ('Biblioteca', 'Biblioteca'), ('Multipropósito', 'Multipropósito')], max_length=50, verbose_name='Tipo de Aula')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad del Aula')),
                ('ubicacion', models.CharField(choices=[('Centro Minero', 'Centro Minero'), ('CEDEAGRO', 'CEDEAGRO'), ('CEGAFE', 'CEGAFE'), ('Sede Sogamoso', 'Sede Sogamoso')], max_length=50, verbose_name='Ubicación')),
                ('proyector', models.BooleanField(default=False, verbose_name='Proyector')),
                ('tablero_digital', models.BooleanField(default=False, verbose_name='Tablero Digital')),
                ('computadores', models.BooleanField(default=False, verbose_name='Computadores')),
                ('sistema_sonido', models.BooleanField(default=False, verbose_name='Sistema de Sonido')),
                ('aire_acondicionado', models.BooleanField(default=False, verbose_name='Aire Acondicionado')),
                ('wifi', models.BooleanField(default=False, verbose_name='WiFi')),
                ('estado_aula', models.CharField(max_length=50, verbose_name='Estado del Aula')),
                ('descripcion_adicional', models.TextField(blank=True, verbose_name='Descripción Adicional')),
            ],
        ),
    ]
